services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
      cache:
        condition: service_healthy
    command: yarn dev

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'bash', '-c', "echo 'db.runCommand({ ping: 1 })' | mongosh localhost:27017 --quiet"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  cache:
    image: redis:latest
    container_name: cache
    ports:
      - '6379:6379'
    volumes:
      - cache_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
volumes:
  mongo_data:
  cache_data:
